# Generated by Django 4.0.2 on 2022-03-05 10:01

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LinkLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Link Location',
                'verbose_name_plural': 'Link Locations',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название страницы')),
                ('title_ru', models.CharField(max_length=100, null=True, verbose_name='Название страницы')),
                ('title_en', models.CharField(max_length=100, null=True, verbose_name='Название страницы')),
                ('content', ckeditor.fields.RichTextField(blank=True, verbose_name='Содержание')),
                ('content_ru', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Содержание')),
                ('content_en', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Содержание')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Slug страницы')),
                ('linklocation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.linklocation', verbose_name='Link Locations')),
            ],
            options={
                'verbose_name': 'Страницу',
                'verbose_name_plural': 'Страницы',
            },
        ),
    ]
