# Generated by Django 4.0.2 on 2023-04-16 11:12

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LinkLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Link Location',
                'verbose_name_plural': 'Link Locations',
            },
        ),
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=150, verbose_name='Название')),
                ('url', models.CharField(default='', max_length=255, verbose_name='Ссылка')),
                ('image', models.ImageField(upload_to='images/partners/', verbose_name='Лого')),
            ],
            options={
                'verbose_name': 'Логотип',
                'verbose_name_plural': 'Логотипы',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=0)),
                ('title', models.CharField(default='', max_length=255, verbose_name='Должность')),
                ('title_ru', models.CharField(default='', max_length=255, null=True, verbose_name='Должность')),
                ('title_en', models.CharField(default='', max_length=255, null=True, verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название страницы')),
                ('title_ru', models.CharField(max_length=100, null=True, verbose_name='Название страницы')),
                ('title_en', models.CharField(max_length=100, null=True, verbose_name='Название страницы')),
                ('content', ckeditor.fields.RichTextField(blank=True, verbose_name='Содержание')),
                ('content_ru', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Содержание')),
                ('content_en', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Содержание')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Slug страницы')),
                ('linklocation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.linklocation', verbose_name='Link Locations')),
            ],
            options={
                'verbose_name': 'Страницу',
                'verbose_name_plural': 'Страницы',
            },
        ),
        migrations.CreateModel(
            name='EditorialMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=0)),
                ('full_name', models.CharField(default='', max_length=255, verbose_name='Ф.И.О.')),
                ('full_name_ru', models.CharField(default='', max_length=255, null=True, verbose_name='Ф.И.О.')),
                ('full_name_en', models.CharField(default='', max_length=255, null=True, verbose_name='Ф.И.О.')),
                ('location', models.CharField(default='', max_length=255, verbose_name='Место работы')),
                ('location_ru', models.CharField(default='', max_length=255, null=True, verbose_name='Место работы')),
                ('location_en', models.CharField(default='', max_length=255, null=True, verbose_name='Место работы')),
                ('about', ckeditor.fields.RichTextField(verbose_name='Об авторе')),
                ('about_ru', ckeditor.fields.RichTextField(null=True, verbose_name='Об авторе')),
                ('about_en', ckeditor.fields.RichTextField(null=True, verbose_name='Об авторе')),
                ('e_mail', models.EmailField(max_length=255, verbose_name='E-mail')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Slug страницы')),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.post', verbose_name='Занимаемая должность')),
            ],
            options={
                'verbose_name': 'Участника редакции',
                'verbose_name_plural': 'Редакция',
                'ordering': ['position'],
            },
        ),
    ]
