# Generated by Django 4.0.2 on 2023-04-16 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Logo',
        ),
    ]
