# Generated by Django 4.0.2 on 2023-04-16 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_delete_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, verbose_name='Slug страницы'),
        ),
    ]
