# Generated by Django 4.0.2 on 2022-03-19 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_editorialmember_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editorialmember',
            name='address',
        ),
        migrations.RemoveField(
            model_name='editorialmember',
            name='address_en',
        ),
        migrations.RemoveField(
            model_name='editorialmember',
            name='address_ru',
        ),
        migrations.RemoveField(
            model_name='editorialmember',
            name='e_mail_en',
        ),
        migrations.RemoveField(
            model_name='editorialmember',
            name='e_mail_ru',
        ),
        migrations.RemoveField(
            model_name='editorialmember',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='editorialmember',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='editorialmember',
            name='profile_en',
        ),
        migrations.RemoveField(
            model_name='editorialmember',
            name='profile_ru',
        ),
    ]
