# Generated by Django 4.0.2 on 2022-03-19 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_remove_editorialmember_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editorialmember',
            name='post_en',
        ),
        migrations.RemoveField(
            model_name='editorialmember',
            name='post_ru',
        ),
    ]
