# Generated by Django 4.0.2 on 2023-04-16 11:12

import blogs.models
import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=0)),
                ('title', models.CharField(default='', max_length=255, verbose_name='Заголовок статьи')),
                ('title_ru', models.CharField(default='', max_length=255, null=True, verbose_name='Заголовок статьи')),
                ('title_en', models.CharField(default='', max_length=255, null=True, verbose_name='Заголовок статьи')),
                ('slug', models.SlugField(blank=True, max_length=200, verbose_name='Slug статьи')),
                ('annotation', ckeditor.fields.RichTextField(default='', verbose_name='Аннотация')),
                ('annotation_ru', ckeditor.fields.RichTextField(default='', null=True, verbose_name='Аннотация')),
                ('annotation_en', ckeditor.fields.RichTextField(default='', null=True, verbose_name='Аннотация')),
                ('for_quoting', ckeditor.fields.RichTextField(blank=True, default='', null=True, verbose_name='Для цитирования')),
                ('for_quoting_ru', ckeditor.fields.RichTextField(blank=True, default='', null=True, verbose_name='Для цитирования')),
                ('for_quoting_en', ckeditor.fields.RichTextField(blank=True, default='', null=True, verbose_name='Для цитирования')),
                ('literature', ckeditor.fields.RichTextField(blank=True, default='', null=True, verbose_name='Литература')),
                ('literature_ru', ckeditor.fields.RichTextField(blank=True, default='', null=True, verbose_name='Литература')),
                ('literature_en', ckeditor.fields.RichTextField(blank=True, default='', null=True, verbose_name='Литература')),
                ('doi', models.CharField(default='', max_length=255, null=True, verbose_name='DOI ссылка')),
                ('file', models.FileField(null=True, upload_to='files/Article/', verbose_name='Файл (PDF)')),
                ('file_ru', models.FileField(null=True, upload_to='files/Article/', verbose_name='Файл (PDF)')),
                ('file_en', models.FileField(null=True, upload_to='files/Article/', verbose_name='Файл (PDF)')),
                ('tags_text', models.CharField(default='', max_length=255, verbose_name='Ключевые слова')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения')),
                ('upload_to_review_date', models.DateTimeField(auto_now=True, verbose_name='Дата отправки на рассмотрение')),
                ('published_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('status', models.CharField(choices=[('черновик', 'Черновик'), ('рецензируется', 'Рецензируется'), ('отклонено', 'Отклонено'), ('принят', 'Принят'), ('опубликован', 'Опубликован')], default=blogs.models.ArticleStatusEnum['draft'], max_length=100, verbose_name='Статус')),
                ('is_draft', models.BooleanField(default=True, verbose_name='Черновик')),
            ],
            options={
                'verbose_name': 'Статью',
                'verbose_name_plural': 'Статьи',
                'ordering': ['published_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ArticleSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=0)),
                ('title', models.CharField(default='', max_length=255, verbose_name='Название раздела')),
                ('title_ru', models.CharField(default='', max_length=255, null=True, verbose_name='Название раздела')),
                ('title_en', models.CharField(default='', max_length=255, null=True, verbose_name='Название раздела')),
            ],
            options={
                'verbose_name': 'Раздел',
                'verbose_name_plural': 'Разделы статьи',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название статуса')),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Ключевое слово')),
                ('title_ru', models.CharField(max_length=150, null=True, verbose_name='Ключевое слово')),
                ('title_en', models.CharField(max_length=150, null=True, verbose_name='Ключевое слово')),
                ('related_articles_number', models.IntegerField(default=0, verbose_name='Количество связанных статей')),
            ],
            options={
                'verbose_name': 'Ключевое слово',
                'verbose_name_plural': 'Ключевые слова',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='UniqueViewers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Уникального пользователя',
                'verbose_name_plural': 'Уникальные пользователи',
            },
        ),
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Том', max_length=255, verbose_name='Название тома')),
                ('title_ru', models.CharField(default='Том', max_length=255, null=True, verbose_name='Название тома')),
                ('title_en', models.CharField(default='Том', max_length=255, null=True, verbose_name='Название тома')),
                ('doi', models.CharField(default='', max_length=255, verbose_name='DOI ссылка')),
                ('file', models.FileField(blank=True, null=True, upload_to='files/Volume/', verbose_name='Файл (PDF)')),
                ('file_ru', models.FileField(blank=True, null=True, upload_to='files/Volume/', verbose_name='Файл (PDF)')),
                ('file_en', models.FileField(blank=True, null=True, upload_to='files/Volume/', verbose_name='Файл (PDF)')),
                ('published_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('qr', models.ImageField(blank=True, upload_to='images/volumes/QR/', verbose_name='QR-код')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, verbose_name='Slug тома')),
                ('status_str', models.CharField(blank=True, max_length=100, verbose_name='Строка статуса')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blogs.state', verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Том',
                'verbose_name_plural': 'Тома',
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_file', models.FileField(null=True, upload_to='files/Article/response/', verbose_name='Файл рецензии')),
                ('published_date', models.DateTimeField(auto_now=True, verbose_name='Время комментирования')),
                ('is_recommended', models.BooleanField(default=False, verbose_name='Рекомендация')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_article', to='blogs.article', verbose_name='Статья')),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_comment', to='profiles.reviewersprofile', verbose_name='Рецензент')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=70, verbose_name='Имя')),
                ('first_name_ru', models.CharField(default='', max_length=70, null=True, verbose_name='Имя')),
                ('first_name_en', models.CharField(default='', max_length=70, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(default='', max_length=70, verbose_name='Фамилия')),
                ('last_name_ru', models.CharField(default='', max_length=70, null=True, verbose_name='Фамилия')),
                ('last_name_en', models.CharField(default='', max_length=70, null=True, verbose_name='Фамилия')),
                ('middle_name', models.CharField(default='', max_length=70, verbose_name='Отчество')),
                ('middle_name_ru', models.CharField(default='', max_length=70, null=True, verbose_name='Отчество')),
                ('middle_name_en', models.CharField(default='', max_length=70, null=True, verbose_name='Отчество')),
                ('country', django_countries.fields.CountryField(default='', max_length=2, verbose_name='Страна')),
                ('institution', models.CharField(default='', max_length=255, verbose_name='Учреждение')),
                ('department', models.CharField(default='', max_length=255, verbose_name='Кафедра. отделение')),
                ('post', models.CharField(default='', max_length=255, verbose_name='Должность')),
                ('degree', models.CharField(choices=[('Нет степени', 'Нет степени')], default='', max_length=30, verbose_name='Степень')),
                ('rank', models.CharField(choices=[('Нет звания', 'Активный')], default='', max_length=30, verbose_name='Звание')),
                ('orcid', models.CharField(default='', max_length=100, verbose_name='ORCID')),
                ('scopus_id', models.CharField(default='', max_length=100, verbose_name='Scopus id')),
                ('wos_id', models.CharField(default='', max_length=100, verbose_name='Wos id')),
                ('spin_code_e_library', models.CharField(default='', max_length=100, verbose_name='Spin code e-library')),
                ('slug', models.SlugField(max_length=200, null=True, unique=True, verbose_name='Slug автора')),
                ('linked_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='profile', to='profiles.authorsprofile', verbose_name='Профиль регистрации')),
            ],
            options={
                'verbose_name': 'Автора',
                'verbose_name_plural': 'Авторы',
                'ordering': ['last_name'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='authors',
            field=models.ManyToManyField(blank=True, related_name='authors', to='blogs.Authors', verbose_name='Связанные Авторы'),
        ),
        migrations.AddField(
            model_name='article',
            name='chapter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='blogs.articlesection', verbose_name='Раздел'),
        ),
        migrations.AddField(
            model_name='article',
            name='linked_volume',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='blogs.volume', verbose_name='Связанный том'),
        ),
        migrations.AddField(
            model_name='article',
            name='profile_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='authors', to='profiles.authorsprofile', verbose_name='Связанные Авторы'),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(related_name='tags', to='blogs.Tags', verbose_name='Ключевые слова'),
        ),
        migrations.AddField(
            model_name='article',
            name='viewers',
            field=models.ManyToManyField(related_name='viewers', to='blogs.UniqueViewers', verbose_name='Просмотры'),
        ),
    ]
