# Generated by Django 4.0.2 on 2022-03-05 10:01

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='Ф.И.О.')),
            ],
            options={
                'verbose_name': 'Автора',
                'verbose_name_plural': 'Авторы',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название статуса')),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
            },
        ),
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Том', max_length=255, verbose_name='Название тома')),
                ('title_ru', models.CharField(default='Том', max_length=255, null=True, verbose_name='Название тома')),
                ('title_en', models.CharField(default='Том', max_length=255, null=True, verbose_name='Название тома')),
                ('doi', models.CharField(default='', max_length=255, verbose_name='DOI ссылка')),
                ('doi_ru', models.CharField(default='', max_length=255, null=True, verbose_name='DOI ссылка')),
                ('doi_en', models.CharField(default='', max_length=255, null=True, verbose_name='DOI ссылка')),
                ('qr', models.ImageField(upload_to='images/volumes/QR/', verbose_name='QR-код')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, verbose_name='Slug тома')),
                ('status_str', models.CharField(blank=True, max_length=100, verbose_name='Строка статуса')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blogs.state', verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Том',
                'verbose_name_plural': 'Тома',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255, verbose_name='Заголовок статьи')),
                ('title_ru', models.CharField(default='', max_length=255, null=True, verbose_name='Заголовок статьи')),
                ('title_en', models.CharField(default='', max_length=255, null=True, verbose_name='Заголовок статьи')),
                ('annotation', ckeditor.fields.RichTextField(default='', verbose_name='Аннотация')),
                ('annotation_ru', ckeditor.fields.RichTextField(default='', null=True, verbose_name='Аннотация')),
                ('annotation_en', ckeditor.fields.RichTextField(default='', null=True, verbose_name='Аннотация')),
                ('doi', models.CharField(default='', max_length=255, null=True, verbose_name='DOI ссылка')),
                ('doi_ru', models.CharField(default='', max_length=255, null=True, verbose_name='DOI ссылка')),
                ('doi_en', models.CharField(default='', max_length=255, null=True, verbose_name='DOI ссылка')),
                ('qr', models.ImageField(upload_to='image/articles/QR/', verbose_name='QR-код')),
                ('published_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('slug', models.SlugField(blank=True, max_length=200, verbose_name='Slug статьи')),
                ('is_active', models.BooleanField(default=False, verbose_name='Показывать на сайте')),
                ('authors', models.ManyToManyField(related_name='authors', to='blogs.Authors', verbose_name='Авторы')),
                ('linked_volume', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='blogs.volume', verbose_name='Связанный том')),
            ],
            options={
                'verbose_name': 'Статью',
                'verbose_name_plural': 'Статьи',
            },
        ),
    ]
