# Generated by Django 4.0.2 on 2023-04-25 13:25

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='country',
            field=django_countries.fields.CountryField(default='Uzbekistan', max_length=2, verbose_name='Страна'),
        ),
    ]
