# Generated by Django 4.0.2 on 2022-03-05 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='doi_en',
        ),
        migrations.RemoveField(
            model_name='article',
            name='doi_ru',
        ),
    ]
