# Generated by Django 4.0.2 on 2022-03-05 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_remove_article_doi_en_remove_article_doi_ru'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volume',
            name='doi_en',
        ),
        migrations.RemoveField(
            model_name='volume',
            name='doi_ru',
        ),
    ]
