# Generated by Django 4.0.2 on 2023-04-25 13:30

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_alter_authors_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='city',
            field=models.CharField(default='', max_length=100, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='authors',
            name='country',
            field=django_countries.fields.CountryField(default='UZ', max_length=2, verbose_name='Страна'),
        ),
    ]
