# Generated by Django 4.0.2 on 2022-03-05 16:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_remove_volume_doi_en_remove_volume_doi_ru'),
    ]

    operations = [
        migrations.AddField(
            model_name='volume',
            name='published_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата публикации'),
        ),
    ]
