# Generated by Django 4.0.2 on 2022-03-05 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_volume_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='name_en',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='Ф.И.О.'),
        ),
        migrations.AddField(
            model_name='authors',
            name='name_ru',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='Ф.И.О.'),
        ),
    ]
