# Generated by Django 4.0.2 on 2022-03-08 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_authors_name_en_authors_name_ru'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['published_date', 'title'], 'verbose_name': 'Статью', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AddField(
            model_name='volume',
            name='file',
            field=models.FileField(null=True, upload_to='files/Volume/', verbose_name='Файл'),
        ),
    ]
