# Generated by Django 4.0.2 on 2022-03-08 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_alter_article_options_volume_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volume',
            name='file',
        ),
        migrations.AddField(
            model_name='article',
            name='file',
            field=models.FileField(null=True, upload_to='files/Volume/', verbose_name='Файл (PDF)'),
        ),
    ]
