# Generated by Django 4.0.2 on 2022-03-08 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_alter_article_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='file_en',
            field=models.FileField(null=True, upload_to='files/Article/', verbose_name='Файл (PDF)'),
        ),
        migrations.AddField(
            model_name='article',
            name='file_ru',
            field=models.FileField(null=True, upload_to='files/Article/', verbose_name='Файл (PDF)'),
        ),
    ]
