# Generated by Django 4.0.2 on 2022-03-14 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0009_article_file_en_article_file_ru'),
    ]

    operations = [
        migrations.AddField(
            model_name='volume',
            name='file',
            field=models.FileField(null=True, upload_to='files/Volume/', verbose_name='Файл (PDF)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='qr',
            field=models.ImageField(upload_to='images/articles/QR/', verbose_name='QR-код'),
        ),
    ]
