# Generated by Django 4.0.2 on 2022-03-14 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0010_volume_file_alter_article_qr'),
    ]

    operations = [
        migrations.AddField(
            model_name='volume',
            name='file_en',
            field=models.FileField(null=True, upload_to='files/Volume/', verbose_name='Файл (PDF)'),
        ),
        migrations.AddField(
            model_name='volume',
            name='file_ru',
            field=models.FileField(null=True, upload_to='files/Volume/', verbose_name='Файл (PDF)'),
        ),
    ]
