# Generated by Django 4.0.2 on 2022-03-14 13:52

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0011_volume_file_en_volume_file_ru'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='for_quoting',
            field=ckeditor.fields.RichTextField(default='', verbose_name='Для цитирования'),
        ),
    ]
