# Generated by Django 4.0.2 on 2022-03-14 13:54

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0012_article_for_quoting'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='for_quoting_en',
            field=ckeditor.fields.RichTextField(default='', null=True, verbose_name='Для цитирования'),
        ),
        migrations.AddField(
            model_name='article',
            name='for_quoting_ru',
            field=ckeditor.fields.RichTextField(default='', null=True, verbose_name='Для цитирования'),
        ),
    ]
