# Generated by Django 4.0.2 on 2022-03-14 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0014_articlesection_article_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlesection',
            name='title_en',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='Название раздела'),
        ),
        migrations.AddField(
            model_name='articlesection',
            name='title_ru',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='Название раздела'),
        ),
    ]
