# Generated by Django 4.0.2 on 2022-03-14 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0015_articlesection_title_en_articlesection_title_ru'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Ключевое слово')),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
            },
        ),
        migrations.AlterField(
            model_name='volume',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/Volume/', verbose_name='Файл (PDF)'),
        ),
        migrations.AlterField(
            model_name='volume',
            name='file_en',
            field=models.FileField(blank=True, null=True, upload_to='files/Volume/', verbose_name='Файл (PDF)'),
        ),
        migrations.AlterField(
            model_name='volume',
            name='file_ru',
            field=models.FileField(blank=True, null=True, upload_to='files/Volume/', verbose_name='Файл (PDF)'),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(related_name='tags', to='blogs.Tags', verbose_name='Теги'),
        ),
    ]
