# Generated by Django 4.0.2 on 2022-03-14 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0016_tags_alter_volume_file_alter_volume_file_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags',
            name='title_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Ключевое слово'),
        ),
        migrations.AddField(
            model_name='tags',
            name='title_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Ключевое слово'),
        ),
    ]
