# Generated by Django 4.0.2 on 2022-03-15 15:37

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0018_alter_tags_options_article_position_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['position', 'published_date', 'title'], 'verbose_name': 'Статью', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AlterField(
            model_name='article',
            name='for_quoting',
            field=ckeditor.fields.RichTextField(blank=True, default='', null=True, verbose_name='Для цитирования'),
        ),
        migrations.AlterField(
            model_name='article',
            name='for_quoting_en',
            field=ckeditor.fields.RichTextField(blank=True, default='', null=True, verbose_name='Для цитирования'),
        ),
        migrations.AlterField(
            model_name='article',
            name='for_quoting_ru',
            field=ckeditor.fields.RichTextField(blank=True, default='', null=True, verbose_name='Для цитирования'),
        ),
    ]
