# Generated by Django 4.0.2 on 2022-03-17 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0019_alter_article_options_alter_article_for_quoting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlesection',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
