# Generated by Django 4.0.2 on 2022-03-17 15:07

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0020_articlesection_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlesection',
            options={'ordering': ['position'], 'verbose_name': 'Раздел', 'verbose_name_plural': 'Разделы статьи'},
        ),
        migrations.AddField(
            model_name='article',
            name='literature',
            field=ckeditor.fields.RichTextField(blank=True, default='', null=True, verbose_name='Литература'),
        ),
    ]
