# Generated by Django 4.0.2 on 2022-03-18 16:18

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0021_alter_articlesection_options_article_literature'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='literature_en',
            field=ckeditor.fields.RichTextField(blank=True, default='', null=True, verbose_name='Литература'),
        ),
        migrations.AddField(
            model_name='article',
            name='literature_ru',
            field=ckeditor.fields.RichTextField(blank=True, default='', null=True, verbose_name='Литература'),
        ),
    ]
