# Generated by Django 4.0.2 on 2022-03-24 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0022_article_literature_en_article_literature_ru'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, verbose_name='Slug тома'),
        ),
    ]
