# Generated by Django 4.0.2 on 2022-04-06 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0025_tags_related_articles_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authors',
            options={'ordering': ['position'], 'verbose_name': 'Автора', 'verbose_name_plural': 'Авторы'},
        ),
        migrations.AddField(
            model_name='authors',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
