# Generated by Django 4.0.2 on 2022-04-06 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0026_alter_authors_options_authors_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniqueViewers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Уникального пользователя',
                'verbose_name_plural': 'Уникальные пользователи',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='viewers',
            field=models.ManyToManyField(related_name='viewers', to='blogs.UniqueViewers', verbose_name='Просмотры'),
        ),
    ]
