# Generated by Django 4.0.2 on 2022-04-10 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0027_uniqueviewers_article_viewers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='viewers',
            field=models.ManyToManyField(blank=True, null=True, related_name='viewers', to='blogs.UniqueViewers', verbose_name='Просмотры'),
        ),
        migrations.AlterField(
            model_name='authors',
            name='slug',
            field=models.SlugField(max_length=200, null=True, verbose_name='Slug тома'),
        ),
    ]
