# Generated by Django 4.0.2 on 2022-04-10 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0028_alter_article_viewers_alter_authors_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='viewers',
            field=models.ManyToManyField(related_name='viewers', to='blogs.UniqueViewers', verbose_name='Просмотры'),
        ),
    ]
