# Generated by Django 4.0.2 on 2022-07-10 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0029_alter_article_viewers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authors',
            options={'verbose_name': 'Автора', 'verbose_name_plural': 'Авторы'},
        ),
        migrations.AlterModelOptions(
            name='volume',
            options={'ordering': ['-published_date'], 'verbose_name': 'Том', 'verbose_name_plural': 'Тома'},
        ),
    ]
