# Generated by Django 4.0.2 on 2022-07-15 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0030_alter_authors_options_alter_volume_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authors',
            name='position',
        ),
        migrations.AddField(
            model_name='article',
            name='authors_text',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='Авторы'),
        ),
        migrations.AlterField(
            model_name='article',
            name='authors',
            field=models.ManyToManyField(blank=True, related_name='authors', to='blogs.Authors', verbose_name='Связанные Авторы'),
        ),
    ]
