# Generated by Django 4.0.2 on 2022-07-16 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0032_alter_article_options_remove_article_authors_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='position',
        ),
    ]
