# Generated by Django 4.0.2 on 2022-07-18 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0034_article_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authors',
            options={'ordering': ['name_ru'], 'verbose_name': 'Автора', 'verbose_name_plural': 'Авторы'},
        ),
        migrations.AlterModelOptions(
            name='tags',
            options={'ordering': ['title'], 'verbose_name': 'Ключевое слово', 'verbose_name_plural': 'Ключевые слова'},
        ),
        migrations.AddField(
            model_name='article',
            name='authors_text',
            field=models.CharField(default='', max_length=255, verbose_name='Авторы (Текст)'),
        ),
    ]
