# Generated by Django 4.0.2 on 2022-09-10 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0035_alter_authors_options_alter_tags_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='authors_text_en',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='Авторы (Текст)'),
        ),
        migrations.AddField(
            model_name='article',
            name='authors_text_ru',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='Авторы (Текст)'),
        ),
    ]
